---
title: "Iteration"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Get Sample

```{r}
x_vec = rnorm(30, mean = 10, sd = 5)

x_vec

mean(x_vec)

sd(x_vec)

(x_vec - mean(x_vec)) / sd(x_vec)
```
z_score function a number minuous mean over the sd


## Function


### Simple function for z_score

```{r}
z_score_1 = function(x){
  
  z = (x-mean(x)) / sd(x)
  
  return(z)
  
}

z_score_1(x_vec)
```


### Complex function

```{r}
z_score_2 = function(x) {
  
  if (!is.numeric(x)) {
    stop("input must be numeric")
  }
  
  if (length(x)<5) {
    stop("input must exceed 5 objects")
  }
  
  z = (x-mean(x)) / sd(x)
  
  return(z)
  
}

z_score_2(x_vec)
```


### with other input

```{r, error=TRUE}
z_score_2(3)

z_score_2("i love potato")

z_score_2(mtcars)

z_score_2(c(TRUE, FALSE, TRUE, FALSE))
```

Not working or working in the wrong direction with simple function.



