---
title: "Iteration and list columns"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```



## Lists

### List for everything.

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE),
  mat = matrix(1:8, nrow = 4, ncol = 2),
  summary = summary(rnorm(100))
)
```

### get from list
```{r}
l
l$vec_numeric
l[[1]]
l[["vec_numeric"]][1:3]
mean(l[["vec_numeric"]])
```



## 'for' loop

```{r}
list_norm = list(
  a = rnorm(20, 3, 1),
  b = rnorm(40, 5, 3),
  c = rnorm(60, 0, .2),
  d = rnorm(50, -3, 1)
)
```

```{r}
mean_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("input must be numeric")
  }
  
  if (length(x)<5) {
    stop("input must exceed 5 objects")
  }
  
  mean_x = mean(x)
  
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

### old method

```{r}
mean_sd(list_norm[[1]])
mean_sd(list_norm[[2]])
mean_sd(list_norm[[3]])
mean_sd(list_norm[[4]])
```

### new method

```{r}
output_1 = vector("list", length = 4)

for (i in 1:4) {
  
  output_1[[i]] = mean_sd(list_norm[[i]])
  
}
```



## Map

```{r}
output_2 = map(list_norm, mean_sd)

output_3 = map(list_norm, median)

output_2
output_3
```

```{r}
output_3 = map_dbl(list_norm, median)

output_2 = map_df(list_norm, mean_sd, .id = "input")


output_2
output_3
```



## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm
  )
```

```{r}
listcol_df %>% pull(name)

listcol_df %>% pull(samp)

listcol_df %>% 
  filter(name == "a")
```

```{r}
listcol_df$samp[[1]]

mean_sd(listcol_df$samp[[1]])

map(listcol_df$samp, mean_sd)

listcol_summary =
  listcol_df %>% 
  mutate(
    summary = map(samp, mean_sd),
    medians = map_dbl(samp, median)
  )
```



## Example: Weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

### get nested
```{r}
weather_nest = 
  weather_df %>% 
  nest(data = date:tmin)
```

```{r}
weather_nest %>% pull(name)
weather_nest %>% pull(data)
```

### regression

```{r}
lm(tmax ~ tmin, data = weather_nest$data[[1]])
```

```{r}
weather_lm = function(df) {
  
  lm(tmax ~ tmin, data = df)
  
}

weather_lm(weather_nest$data[[1]])
```

```{r}
output = vector("list", 3)

for (i in 1:3) {
  
  output[i] = weather_lm(weather_nest$data[[i]])
  
}
```

### map

```{r}
map(weather_nest$data, weather_lm)
```

### map in list column

```{r}
weather_reg = 
  weather_nest %>% 
  mutate(models = map(data, weather_lm))

weather_reg$models
```

